apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vk-nginx
  template:
    metadata:
      labels:
        app: vk-nginx
    spec:
      containers:
      - name: nginx
        image: jasonwsuk/vk-nginx
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "cd /etc/nginx/conf.d/ && sed -i 's/GUNICORN_HOST/VIKING_SVC_GU_PORT_8000_TCP_ADDR/g' * && sed -i 's/GUNICORN_PORT/VIKING_SVC_GU_PORT_8000_TCP_PORT/g' * && envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sh"]
        args: ["-c", "while true; do ping localhost; sleep 60;done"]
