apiVersion: apps/v1
kind: Deployment
metadata:
  name: viking-gunicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viking-gunicorn
  template:
    metadata:
      labels:
        app: viking-gunicorn
    spec:
      containers:
      - name: gunicorn
        image: jasonwsuk/vk-gunicorn
        env:
        - name: POSTGRES_DB
          value: viking
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: dkagh12.
        - name: POSTGRES_HOST
          value: postgres-headless.default.svc.cluster.local
        command: ["/bin/sh"]
        args: ["-c", "gunicorn --bind 0:8000 'pybo:create_app()'"]
        ports: 
        - containerPort: 8000
      hostname: slave2p
      subdomain: viking-gunicorn
