apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk-flask
  template:
    metadata:
      labels:
        app: vk-flask
    spec:
      containers:
      - name: flask
        image: jasonwsuk/vk-gunicorn
        env:
        - name: POSTGRES_DB
          value: viking
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: dkagh12.
        - name: POSTGRES_HOST
          value: pgdb-postgresql-ha-postgresql-headless.default.svc.cluster.local 
        command: ["/bin/sh"]
        args: ["-c", "flask run --host=0.0.0.0 && flask db init && flask db migrate && flask db upgrade"]
        ports: 
        - containerPort: 5000
